### ISSUE TITLE
Design and print separate markers for snake, spider etc.

### ISSUE THREAD

**Issue by s-soltys** [HackingHealthHackathonBerlin/iPhobia#1]

**Comment by banksi** [comment]
![logo_arachnophobia_spider](https://cloud.githubusercontent.com/assets/7452838/23335541/b365c382-fbb7-11e6-9ff7-1daebdab0a95.png)
![logo_ophidiophobia_snake](https://cloud.githubusercontent.com/assets/7452838/23335542/b3849262-fbb7-11e6-92b9-40a79112ccc6.png)
![Uploading Logo_Acrophobia_Heights.png…]()
![Uploading Logo_Agoraphobia_OpenSpaces.png…]()
![Uploading Logo_Cynophobia_Dogs.png…]()
![Uploading Cynophobia_Dogs.png…]()
![Uploading Agoraphobia_OpenSpaces.png…]()
![Uploading Acrophobia_Heights.png…]()
![Uploading Ophidiophobia_Snake.png…]()
![Uploading Arachnophobia_Spider.png…]()
