### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by s-soltys** [HackingHealthHackathonBerlin/iPhobia#2]

**Comment by banksi** [comment]
Added to Assets/Docs
![logo](https://cloud.githubusercontent.com/assets/7452838/23335365/caed83d0-fbb4-11e6-8208-057edbe294db.jpg)
<img width="128" alt="logo" src="https://cloud.githubusercontent.com/assets/7452838/23335366/caf5a8d0-fbb4-11e6-92d5-3174848ba400.png">
